# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=256, null=True, upload_to=b''),
        ),
    ]
