# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=256, null=True, upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=256),
        ),
    ]
